[package]
name = "shader_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
app_base.workspace = true
log.workspace = true
renderer.workspace = true
window.workspace = true
shader_editor_lib.workspace = true